### ISSUE TITLE
"decf" and "incf" causing errors

### ISSUE THREAD

**Issue by Koiane** [rudi/maude-mode#1]
I'm really an amateur at this, so bear with me. 

From *messages*:
Warning (comp): maude-mode.el:769:14: Warning: the function ‘decf’ is not known to be defined. Disable showing Disable logging
Warning (comp): maude-mode.el:751:14: Warning: the function ‘incf’ is not known to be defined. Disable showing Disable logging

After some searching, I found a [possible solution](https://github.com/prettier/prettier/pull/138): "use setq' instead of incf' and `decf'"

Simply query-replacing all instances of 'decf' and 'incf' with 'setq' removes the error messages, and produces what at least so far seems like the desired behavior.

**Comment by rudi** [comment]
Thanks for the heads-up, and sorry for the late reply!  I decided to use cl-lib instead, which provides cl-incf and cl-decf.
